name: $(Date:yyyy.M.d)$(Rev:.r)

parameters:
  - name: runRushAudit
    type: boolean
    default: true

variables:
  currentNodeVersion: "26.8.1"
  maintenanceNodeVersion: "22.23.2"

trigger: none

jobs:
  - job: BuildAndTest
    strategy:
      matrix:
        linux-node-current:
          imageName: "ubuntu-latest"
          nodeVersion: $(currentNodeVersion)
          runFrontendIntegrationTests: true
        windows-node-current:
          imageName: "windows-latest"
          nodeVersion: $(currentNodeVersion)
          runFrontendIntegrationTests: true
        windows-node-maintenance:
          imageName: "windows-latest"
          nodeVersion: $(maintenanceNodeVersion)
          runFrontendIntegrationTests: true
    pool:
      vmImage: $(imageName)
    variables:
      - group: object-storage - Integration Tests Variables
    workspace:
      clean: all

    steps:
      - template: templates/build-test.yml
        parameters:
          runRushAudit: ${{ parameters.runRushAudit }}
