name:
  $(Date:yyyy.M.d)$(Rev:.r)

parameters:
- name: runRushAudit
  type: boolean
  default: true

trigger: none

jobs:
  - job: BuildAndTest
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-latest'
        windows:
          imageName: 'windows-latest'
    pool:
        vmImage: $(imageName)
    variables:
      - group: object-storage - Integration Tests Variables
    workspace:
      clean: all

    steps:
    - template: templates/build-test.yml
      parameters:
        runRushAudit: ${{ parameters.runRushAudit }}
