name:
  $(Date:yyyy.M.d)$(Rev:.r)

parameters:
- name: runRushAudit
  type: boolean
  default: true

variables:
  node18Version: '18.13.0'
  node16Version: '16.15.0'
  node12Version: '12.17.0'

trigger: none

jobs:
  - job: BuildAndTest
    strategy:
      matrix:
        linux-node-18:
          imageName: 'ubuntu-latest'
          nodeVersion: $(node18Version)
          runFrontendIntegrationTests: true
        windows-node-18:
          imageName: 'windows-latest'
          nodeVersion: $(node18Version)
          runFrontendIntegrationTests: true
        linux-node-16:
          imageName: 'ubuntu-latest'
          nodeVersion: $(node16Version)
          runFrontendIntegrationTests: true
        windows-node-16:
          imageName: 'windows-latest'
          nodeVersion: $(node16Version)
          runFrontendIntegrationTests: true
        linux-node-12:
          imageName: 'ubuntu-latest'
          nodeVersion: $(node12Version)
          runFrontendIntegrationTests: false
        windows-node-12:
          imageName: 'windows-latest'
          nodeVersion: $(node12Version)
          runFrontendIntegrationTests: false
    pool:
        vmImage: $(imageName)
    variables:
      - group: object-storage - Integration Tests Variables
    workspace:
      clean: all

    steps:
    - template: templates/build-test.yml
      parameters:
        runRushAudit: ${{ parameters.runRushAudit }}

  - job: Publish
    dependsOn: BuildAndTest
    pool: 
      vmImage: 'windows-latest'
   
    steps:
    - template: templates/publish.yml
