parameters:
- name: runRushAudit
  type: boolean
  default: true

steps:
  - task: NodeTool@0
    displayName: Install Node@14.17.5
    inputs:
      versionSpec: '14.17.5'
      checkLatest: true

  - script: node common/scripts/install-run-rush.js install --purge
    displayName: rush install

  - script: node common/scripts/install-run-rush.js audit
    displayName: rush audit
    condition: and(succeeded(), eq('${{ parameters.runRushAudit }}', true))

  - script: node common/scripts/install-run-rush.js rebuild -v
    displayName: rush rebuild

  - script: node common/scripts/install-run-rush.js lint
    displayName: rush lint

  - script: node common/scripts/install-run-rush.js spell-check
    displayName: rush spell-check

  - script: node common/scripts/install-run-rush.js test
    displayName: rush test

  - script: npm run test:integration:backend
    displayName: npm run test:integration:backend (OSS)
    workingDirectory: storage/oss
    env:
      TEST_OSS_ACCESS_KEY: $(TEST_OSS_ACCESS_KEY)
      TEST_OSS_SECRET_KEY: $(TEST_OSS_SECRET_KEY)
      TEST_OSS_ROLE_ARN: $(TEST_OSS_ROLE_ARN)

  - script: npm run test:integration:backend
    displayName: npm run test:integration:backend (Azure)
    workingDirectory: storage/azure
    env:
      TEST_AZURE_STORAGE_ACCOUNT_KEY: $(TEST_AZURE_STORAGE_ACCOUNT_KEY)

  - script: npm run test:integration:backend
    displayName: npm run test:integration:backend (MinIO)
    workingDirectory: storage/minio

  - script: npm run test:integration:frontend
    displayName: npm run test:integration:frontend (OSS)
    workingDirectory: storage/oss
    env:
      TEST_OSS_ACCESS_KEY: $(TEST_OSS_ACCESS_KEY)
      TEST_OSS_SECRET_KEY: $(TEST_OSS_SECRET_KEY)
      TEST_OSS_ROLE_ARN: $(TEST_OSS_ROLE_ARN)

  - script: npm run test:integration:frontend
    displayName: npm run test:integration:frontend (Azure)
    workingDirectory: storage/azure
    env:
      TEST_AZURE_STORAGE_ACCOUNT_KEY: $(TEST_AZURE_STORAGE_ACCOUNT_KEY)

  - script: npm run test:integration:frontend
    displayName: npm run test:integration:frontend (MinIO)
    workingDirectory: storage/minio
